# Linear Algebra and Embeddings

(C) 2023-2024 by [Damir Cavar](http://damir.cavar.me/)

**Prerequisites:**

In [ ]:
!pip install -U numpy

In [ ]:
!pip install -U pip setuptools wheel

The following installation of spaCy is ideal for my environment, i.e., using a GPU and CUDA 12.x. See the [spaCy homepage](https://spacy.io/usage) for detailed installation instructions.

In [ ]:
!pip install -U 'spacy[cuda12x,transformers,lookups,ja]'

Installing language module:

In [ ]:
!python -m spacy download en_core_web_trf

## Using spaCy Word Embeddings



In [1]:
import spacy
import numpy as np

In [25]:
nlp = spacy.load("en_core_web_lg")

In [31]:
doc = nlp("This is a text")
doc.vector

array([-1.0969249 ,  3.5422752 ,  0.23759246, -0.555475  ,  5.2427    ,
       -2.4753752 ,  2.3339748 ,  2.8237414 ,  0.33422732, -0.3434676 ,
       12.083975  ,  0.33232486, -3.362825  , -1.320285  ,  0.388     ,
        4.3468122 ,  3.9268746 ,  6.310725  ,  1.81281   ,  3.459995  ,
       -0.60847497,  0.6960525 , -3.12215   ,  1.7629642 , -3.78505   ,
       -3.615975  , -2.401775  , -3.773425  , -4.586575  , -0.17040491,
       -2.2923126 ,  0.20159996, -2.092505  , -0.081205  , -3.5820775 ,
        1.7506775 , -0.04733169, -1.336425  ,  6.71595   , -1.0187502 ,
       -3.2500327 ,  1.653998  , -1.67977   ,  0.19409996, -1.7241253 ,
        3.2048974 ,  5.43085   , -2.63674   , -3.197685  , -0.8757375 ,
       -1.1576226 , -1.9054224 ,  4.32505   , -3.5928502 , -0.06439996,
       -0.49245   ,  3.9352    ,  0.5091    , -1.5124725 , -1.2777625 ,
        3.9715326 ,  1.292665  , -1.6772001 , -0.33407497, -3.6834948 ,
        4.0337377 , -2.8430524 , -8.60705   ,  3.8568497 ,  3.18

In [28]:
doc_v = [ v.vector for v in doc ]

In [9]:
a = np.array([ 1.0, 2.0 ])
b = np.array([ 2.0, 3.0 ])
(a + b) / 2.0

array([1.5, 2.5])

In [30]:
c = [ a, b ]
sum(c) / len(c)

array([1.5, 2. ])

In [10]:
np.mean([a, b], dtype=float)

2.0

In [11]:
np.mean([a, b], dtype=float, axis=0)

array([1.5, 2.5])