# Matrix Operations for FSA Computing

**(C) 2017-2020 by [Damir Cavar](http://damir.cavar.me/)**

**Download:** This and various other Jupyter notebooks are available from my [GitHub repo](https://github.com/dcavar/python-tutorial-notebooks).

**Version:** 1.2, September 2020

**License:** [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/) ([CA BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/))

In [2]:
import numpy as np

In [3]:
a = np.array([[1, 1, 0],
             [1, 0, 0],
             [0, 0, 0]])

In [4]:
a

array([[1, 1, 0],
       [1, 0, 0],
       [0, 0, 0]])

In [5]:
b = np.array([[0, 1, 0],
             [0, 1, 0],
             [0, 0, 0]])


In [6]:
c = np.array([[0, 0, 0],
            [0, 0, 1],
            [0, 0, 0]])

In [7]:
init = np.array([1, 0, 0])

In [8]:
init

array([1, 0, 0])

In [9]:
final = np.array([[0],
                 [0],
                 [1]])

In [10]:
final

array([[0],
       [0],
       [1]])

In [11]:
init.dot(a.dot(b.dot(c))).dot(final)

array([2])

In [12]:
init.dot(a.dot(a.dot(c.dot(c)))).dot(final)

array([0])