# A Simple Feed Forward Neural Network from Scratch

(C) 2023 by [Damir Cavar](http://damir.cavar.me/)


In [1]:
import numpy as np

In [9]:
x = np.array([2, 3, 4, 5, 6, 7])
num_features = 5
W = np.random.rand(len(x), num_features)
b = np.random.rand(num_features)

In [27]:
x_reshaped = x.reshape(len(x), 1)
print(x_reshaped.T)
print(x_reshaped)


[[2 3 4 5 6 7]]
[[2]
 [3]
 [4]
 [5]
 [6]
 [7]]


In [8]:
W

array([[0.46075016, 0.90433791, 0.37406317, 0.41519262, 0.33529596],
       [0.09541445, 0.56952051, 0.64697407, 0.22125264, 0.82742156],
       [0.73346318, 0.03653096, 0.73059091, 0.66508867, 0.17072621],
       [0.3663648 , 0.78451048, 0.50580827, 0.02198189, 0.07921299],
       [0.38292082, 0.54110659, 0.26658554, 0.62745405, 0.87700375],
       [0.7966569 , 0.90560272, 0.26297394, 0.48049441, 0.19984668]])

In [10]:
b

array([0.94950631, 0.45440971, 0.33162325, 0.40384779, 0.71634556])

In [31]:
z = x_reshaped.T @ W + b

In [32]:
print(z)

[[17.16569332  7.11120556 13.62192661  7.31092348 12.5430463 ]]


In [39]:
def relu(x):
    return np.maximum(0,x)

In [44]:
a = relu(z)
a

array([[17.16569332,  7.11120556, 13.62192661,  7.31092348, 12.5430463 ]])

In [45]:
U = np.random.rand(len(a[0]), 1)

In [46]:
U

array([[0.28574536],
       [0.92975633],
       [0.29562202],
       [0.5270413 ],
       [0.30204148]])

In [50]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [58]:
z2 = a @ U
print(z2)
sigmoid(z2[0][0])

[[23.18532608]]


0.9999999999147409

## Sentiment Analysis Example

In [1]:
import os
import csv

In [2]:
experiment_data = []
with open(os.path.join('.', 'data', 'reviews.csv'), newline='') as csvfile:
    datareader = csv.reader(csvfile, delimiter=',', quotechar='"')
    header = next(datareader)
    for row in datareader:
        if len(row) == 2:
            experiment_data.append( [row[0].strip(), int(row[1].strip())] )

In [4]:
print(experiment_data[:2])
print("Text:\n", experiment_data[0][0])
print("Value:\n", experiment_data[0][1])


[["Once again Mr. Costner has dragged out a movie for far longer than necessary. Aside from the terrific sea rescue sequences, of which there are very few I just did not care about any of the characters. Most of us have ghosts in the closet, and Costner's character are realized early on, and then forgotten until much later, by which time I did not care. The character we should really care about is a very cocky, overconfident Ashton Kutcher. The problem is he comes off as kid who thinks he's better than anyone else around him and shows no signs of a cluttered closet. His only obstacle appears to be winning over Costner. Finally when we are well past the half way point of this stinker, Costner tells us all about Kutcher's ghosts. We are told why Kutcher is driven to be the best with no prior inkling or foreshadowing. No magic here, it was all I could do to keep from turning it off an hour in.", 0], ["This is an example of why the majority of action films are the same. Generic and boring,

In [5]:
sentiment_dictionary = {}
with open(os.path.join('.', 'data', 'vader_lexicon.txt'), mode='r', encoding='utf-8') as ifile:
    lines = ifile.readlines()
    sentiment_dictionary = { y[0]: y[1] for y in [ x.split('\t') for x in lines ] if len(y) == 4 }

In [6]:
print(sentiment_dictionary["adventurer"])

1.2


In [21]:
from nltk.tokenize import word_tokenize
from collections import Counter
import math
import numpy as np

In [11]:
pronouns = {"i", "me", "my", "mine", "you", "yours", "yourself", "myself", "we", "us", "our", "ours", "ourselves"}

In [15]:
def get_me_the_vector(text):
    tokens = word_tokenize(text.lower())
    scores = [ float(sentiment_dictionary.get(t, 0.0)) for t in tokens ]
    positive = len([ s for s in scores if s > 0 ])
    negative = len([ s for s in scores if s < 0 ])
    if "no" in tokens:
        no_present = 1
    else:
        no_present = 0
    counts = Counter(tokens)
    pronoun_count = 0
    for x in set(counts.keys()).intersection(pronouns):
        pronoun_count += counts[x]
    if "!" in tokens:
        exclamation = 1
    else:
        exclamation = 0
    return (positive, negative, no_present, pronoun_count, exclamation, math.log(len(tokens)))

In [16]:
vectors = [ get_me_the_vector(e[0]) for e in experiment_data ]

In [19]:
print(vectors[1], "\n", experiment_data[1][0])

(13, 8, 0, 3, 0, 5.583496308781699) 
 This is an example of why the majority of action films are the same. Generic and boring, there's really nothing worth watching here. A complete waste of the then barely-tapped talents of Ice-T and Ice Cube, who've each proven many times over that they are capable of acting, and acting well. Don't bother with this one, go see New Jack City, Ricochet or watch New York Undercover for Ice-T, or Boyz n the Hood, Higher Learning or Friday for Ice Cube and see the real deal. Ice-T's horribly cliched dialogue alone makes this film grate at the teeth, and I'm still wondering what the heck Bill Paxton was doing in this film? And why the heck does he always play the exact same character? From Aliens onward, every film I've seen with Bill Paxton has him playing the exact same irritating character, and at least in Aliens his character died, which made it somewhat gratifying... Overall, this is second-rate action trash. There are countless better films to see, a

In [20]:
def relu(x):
    if x > 0: return x
    return 0

In [ ]:
# x = np.array([2, 3, 4, 5, 6, 7])
num_features = 6
num_rows = 3
W = np.random.rand(num_rows, num_features)
b = np.random.rand(num_features)

In [ ]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [ ]:
# we get back a 3-dimensional vector
U = np.random.rand(1, num_rows)
bu = np.random.rand(num_rows)

In [ ]:
results = []
for x, truth in zip(vectors, [ v[1] for v in experiment_data ]):
    x = np.array(x)
    x_reshaped = x.reshape(len(x), 1)
    z = x_reshaped.T @ W + b
    a = relu(z)
    b = sigmoid(a @ U)
    results.append( (truth, b) )

In [23]:
a = [1, 2, 3]
b = ["a", "b", "c"]
list(zip(a, b))

[(1, 'a'), (2, 'b'), (3, 'c')]